Added provisioned concurrency config for cognito trigger
BIBSYSDEV/nva-cognito-pre-token-generation-trigger pull request #33
Opened 2021-01-27 14:00 UTC by janbj

2021-01-27 14:02 UTC, axthosarouris requested changes

2021-01-27 14:02 UTC, axthosarouris commented on template.yaml
> +      AutoPublishAlias: live
Update ApiGateway

2021-01-27 14:43 UTC, janbj commented on template.yaml
> +      AutoPublishAlias: live
No API Gateway in this app

2021-01-28 09:12 UTC, axthosarouris approved these changes

2021-01-28 11:10 UTC, merged